# Generated by Django 4.1.1 on 2023-02-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0005_rename_option_text_option_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='portion',
        ),
    ]
